### API AGENDAMENTO GET
GET http://localhost:8080/api/v2/agendamento



### API AGENDAMENTO POST
POST http://localhost:8080/api/v2/agendamento
Content-Type: application/json

{
    "data e hora": "10:50",
    "status": "concluído",
    "pets": "1",
    "servico": "banho e tosa",
    "cliente": "zezinho de oliveira junior"
}


### API AGENDAMENTO PUT
PUT http://localhost:8080/api/v2/agendamento
Content-Type: application/json

{
    "data e hora": "10:50",
    "status": "concluído",
    "pets": "1",
    "servico": "banho e tosa",
    "cliente": "zezinho de oliveira junior"
}

### API AGENDAMENTO DELETE
DELETE http://localhost:8080/api/v2/agendamento