###  API PEDIDO GET
GET http://localhost:8080/api/v1/pedido


### API PEDIDO POST
POST http://localhost:8080/api/v1/pedido
Content-Type: application/json

{
    "total": "1199",
    "status": "Concluido",
    "cliente": {
                    "id": 1,
                    "nome": "zezinho de oliveira junior",
                    "endereco": "rua lalala 100",
                    "telefone": "5555-1234",
                    "email": "ze@ze.com.br",
                    "dataNascimento": "2025-04-21",
                    "pets": []
                },
    "produtos": [
        {
                    "id": 1,
                    "nome": "Extermina Pulga!",
                    "descricao": null,
                    "quantidade": 5,
                    "preco": 0.0
                }
        ],
    "pagamentos": "Pix"
    
}

### API PEDIDO PUT
PUT http://localhost:8080/api/v1/pedido/1
Content-Type: application/json

{
   "total": "1199",
    "status": "Concluido",
    "cliente": {
                    "id": 1,
                    "nome": "zezinho de oliveira junior",
                    "endereco": "rua lalala 100",
                    "telefone": "5555-1234",
                    "email": "ze@ze.com.br",
                    "dataNascimento": "2025-04-21",
                    "pets": []
                },
    "produtos": [
        {
                    "id": 1,
                    "nome": "Extermina Pulga!",
                    "descricao": null,
                    "quantidade": 5,
                    "preco": 0.0
                }
                ],
    "pagamentos": "Pix"
    
}

### API PEDIDO DELETE
DELETE http://localhost:8080/api/v1/pedido/1