### API PRODUTO GET
GET http://localhost:8080/api/v1/produto


### API PRODUTO POST
POST http://localhost:8080/api/v1/produto
Content-Type: application/json

{
    "nome": "Mata Pulga",
    "descricao": "Eliminando a pulga de seu cachorro, em 5 minutos",
    "quantidade": "5",
    "preco": "129.00"
}

### API PRODUTO PUT
PUT http://localhost:8080/api/v1/produto/1
Content-Type: application/json

{
    "nome": "Extermina Pulga!",
    "descricao": "Eliminando a pulga de seu cachorro, em 5 minutos",
    "quantidade": "5",
    "preco": "129.00"
}

### API PRODUTO DELETE
DELETE http://localhost:8080/api/v1/produto/1