### API SERVICO GET
GET http://localhost:8080/api/v1/servicos


### API SERVICO POST
POST http://localhost:8080/api/v1/servicos
Content-Type: application/json

{
    "tipo": "Banho",
    "descricao": "Banho completo ",
    "preco": "129"
    
}

### API SERVICO PUT
PUT http://localhost:8080/api/v1/servicos/1
Content-Type: application/json

{
    "tipo": "Banho e tosa",
    "descricao": "Banho completo ",
    "preco": "129"
}

### API SERVICO DELETE
DELETE http://localhost:8080/api/v1/servicos/1